name: Leaked Secrets Scan
on: [pull_request]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Get number of commits in branche
      #   run: |
      #     ls
      #     git checkout ${{ env.BRANCH }}
      #     git rev-list master..HEAD | wc -l
      #     echo "commit_count=$(git rev-list --count master..HEAD)" >> $GITHUB_ENV
      - name: Get Commit Difference Count Between Two Branches
        id: cdc
        uses: jessicalostinspace/commit-difference-action@v1.0.0
        with:
          base-branch: HEAD
          secondary-branch: 'master'
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.pull_request.base.ref }}
          head: HEAD
          extra_args: --debug --only-verified --max-depth=${{ steps.cdc.commit-difference-count }}
